---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    run_list:
      - recipe[yum-docker]
    attributes:
      kubernetes:
        master:
          ip: 192.168.33.10

suites:
  # - name: default
  #   run_list:
  #     - recipe[k8s::default]
  #     - recipe[k8s::master]
  #     - recipe[k8s::node]
  #   attributes:
  # - name: docker
  #   run_list:
  #     - recipe[k8s::docker_install]
  #   attributes:
  - name: decker-master
    driver:
      network:
        - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[kubernetes::master]
      - recipe[kubernetes::default]

  - name: decker-worker
    driver:
      network:
        - ["private_network", {ip: "192.168.33.11"}]
    run_list:
      - recipe[kubernetes_test::worker]

  - name: decker-worker-2
    driver:
      network:
        - ["private_network", {ip: "192.168.33.12"}]
    run_list:
      - recipe[kubernetes_test::worker2]

#  - name: node-1
#    run_list:
#      - recipe[k8s::default]
#      - recipe[k8s::node]
#    attributes:
